### ISSUE TITLE
Flag this package as unnecessary with Doctrine DBAL 2.6

### ISSUE THREAD

**Issue by jaikdean** [VasekPurchart/Doctrine-Date-Time-Immutable-Types#12]
`doctrine/dbal` 2.6 has now been released and includes all types in this package. It's probably worth adding a note to the start of the README to let people know.

Bearing in mind `doctrine/dbal` 2.6 requires PHP 7.1, it's worth keeping this package available for users who can't upgrade yet.

**Comment by VasekPurchart** [comment]
Hello, I am working at it at the moment, I will also add a conflicting constraint. I will probably still maintain the [bundle](https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle) because it has the added value, that you can control how the types are registered and I strongly prefer to have immutable types overriding the default ones, in order to minimize risk, that someone writes the default one by accident.

**Comment by VasekPurchart** [comment]
You can check out the corresponding changes here:

* https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types/pull/13
* https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle/pull/22
